language: generic

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx

install:
  # On linux, install Linuxbrew
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    fi

  # Install ourselves as a tap (by hand)
  - brew tap dotboris/alt .

  # For some reason travis has all files setup with mode 664 instead of 644
  - chmod 644 "$(brew --prefix)/Homebrew/Library/Taps/dotboris/homebrew-alt/Formula/"*.rb

script:
  - ./ci/test.py

cache:
  bundler: true
  cargo: true
  directories:
    - $HOME/.cache/Homebrew
    - $HOME/Library/Caches/Homebrew

branches:
  only:
    - master

notifications:
  email:
    on_success: never
