language: generic

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    fi
  - brew tap dotboris/alt .

script:
  - ./ci/test.py

branches:
  only:
    - master

notifications:
  email:
    on_success: never
