language: generic

env:
  global:
    - RUST_BACKTRACE=1
    - HOMEBREW_NO_AUTO_UPDATE=1

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    fi

  - mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dotboris"
  - ln -sT "$(pwd)" "$(brew --prefix)/Homebrew/Library/Taps/dotboris/homebrew-alt"
  - brew tap

script:
  - ./ci/test.py

branches:
  only:
    - master

notifications:
  email:
    on_success: never
