version: '3.7'

volumes:
  brew-cache:

services:
  brew:
    image: homebrew/brew
    volumes:
      - type: bind
        source: .
        target: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/dotboris/homebrew-alt
        read_only: false

      - type: volume
        source: brew-cache
        target: /home/linuxbrew/.cache/Homebrew
        volume:
          nocopy: true

    environment:
      # Preview homebrew from updating the symlinked tap and messing up the repo
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    command:
      - /bin/bash
      - /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/dotboris/homebrew-alt/dev/setup-container.sh
